services:
  db:
    image: postgres:15
    hostname: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .db.env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    env_file:
      - .db.env
    ports:
      - "8888:80"
  flask-api:
    build: 
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./services/api:/services/api 
    env_file:
        - .db.env
  pipeline:
    build: 
      context: .services/fei-data-etl
      dockerfile: Dockerfile
    env_file:
        - .db.env
      
    

  

